### ISSUE TITLE
Game board

### ISSUE THREAD

**Issue by amunds1** [amunds1/LetterLink#20]
**TODO**
- [x] Create a grid using https://mantine.dev/core/grid/ (see localhost:3000/demo)
- [x] Draggable letter which can be placed on the board 
- [x] Get board/letters from Firebase
- [x] Update board UI depending on server checks
- [x] Send changed rows and columns to server using implemented `validateBoard.ts` function
- [x] Regret move
- [x] Show points
- [x] Show letter depending on CHOOSE or PLACE state
- [x] UI for choosing a letter
- [x] Choose who will start the game
- [x] Hide dragging when its opponents turn
- [x] Update value of yourTurn in GameContext locally after PLACE_OWN state
- [x] Save gameState in Firebase, so correct state is set after a reload
- [x] Add listener to nextTurn param in Firebase
- [x] Fix points bug : the whole row/coulmn gets green when one word in the row is valid
- [x] Update local selectedLetter when its your turn
- [x] End the game
- [x] Show opponents points
- [x] Fix bug: Player2 needs to refresh the page to be in the right gameState the first round
- [x] Fix bug: react-beautiful-dnd Invariant failed: Cannot finish a drop animating when no drop is occurring (When you re-drag the letter)
- [x] Update board with colors when results from word check is returned
- [x] Feedback / notifications 
- [x] Show game result after ended game

Styling:
- [x] Submit button become blue when a letter is placed 
- [x] The whole cell should be colored green
- [x] Fixed height on cells

**Comment by amunds1** [comment]
We need to figure out a way to make valid words (green cells) persist. If client state is cleared, the cell colors will be cleared.

Could for instance make a object in Firebase containing information about which cells are supposed to be green.

**Comment by kristinelarssen** [comment]
What do you mean by "_Update board UI depending on server checks_"?

**Comment by kristinelarssen** [comment]
Should the player be able to see some information about the other player's board? Is it intuitive that the board you are seeing, is only yours? 

E.g 
- Feedback / information  that the other players put a valid word: "Player 2 got 3 points for the word "PAI""
- A little snapshot of the other player's board 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/42269602/195336299-a488f8b5-348f-4a5d-b310-c06c6e45e3d3.png">

**Comment by amunds1** [comment]
Good question. Something we should look into
